version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gtlhu55v355f"
s3_prefix = "sam-sam"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
